#! /bin/bash

files='-name core
    -o -name a.out
    -o -name nohup.out
    -o -name dead.letter
'

{ find $HOME \( $files \) -type f -exec /bin/rm -f {} \; 
  find $HOME/.tmp -mtime 60 -exec rm -rf {} \;
} >/dev/null 2>&1
