#! /bin/bash
#  Synopsis:    Col [N_columns]
#  Description: Print columns

ncols=${1:-80}
unset cols
count=1
dec=1
while [ $ncols -ge 10 ]; do
	cols="${cols}123456789${dec}"
	(( count = count + 1 ))
	(( dec = count % 10 ))
	(( ncols = ncols - 10 ))
done

case $ncols in
   9) echo "${cols}123456789" ;;
   8) echo "${cols}12345678" ;;
   7) echo "${cols}1234567" ;;
   6) echo "${cols}123456" ;;
   5) echo "${cols}12345" ;;
   4) echo "${cols}1234" ;;
   3) echo "${cols}123" ;;
   2) echo "${cols}12" ;;
   1) echo "${cols}1" ;;
   0) echo "${cols}" ;;
esac
exit 0
